### ISSUE TITLE
can't install latest version

### ISSUE THREAD

**Issue by beth60197** [deeptools/deepTools#1213]
Hi there,

I installed deeptools using using conda and when running I the following error:

AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.

I checked the version and I had v3.5.1. I tried to update to v3.5.2 but wasn't able to:

`PackagesNotFoundError: The following packages are not available from current channels:

  - deeptools=3.5.2`

**Comment by dpryan79** [comment]
I'll update the version available in bioconda, though I rather doubt that will have an effect on the numpy error you reported. Can you provide the entire error for that?

**Comment by dpryan79** [comment]
Xref: https://github.com/bioconda/bioconda-recipes/pull/40900

**Comment by beth60197** [comment]
I realised dumpy needed upgraded, got it working now!

**Comment by AbhinavSoni20191995** [comment]
Which version of bumpy did you upgrade, I am facing similar issue, but even after updating numpy to 1.24.3 version, I receive similar error

**Comment by AbhinavSoni20191995** [comment]
For me it worked after installing the current version of Deeptools 3.5.2
